USE `goods4goods`;

INSERT INTO AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) VALUES
(1, 'Invalid item reported', 2, 1, 2, 2),
(2, 'Expired offer not processed', 1, 3, 1, 1);
#
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (42, 'platea dictumst', 13, 6, 26, 1);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (28, 'vestibulum eget vulputate ut ultrices', 30, 39, 31, 9);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (47, 'amet nulla', 51, 9, 25, 43);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (2, 'vulputate', 22, 40, 13, 1);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (45, 'eros suspendisse accumsan tortor', 42, 1, 8, 25);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (2, 'nullam porttitor lacus at turpis', 17, 12, 10, 35);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (14, 'vel sem sed', 48, 13, 34, 41);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (15, 'nulla elit ac nulla sed', 27, 15, 12, 2);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (2, 'felis fusce posuere', 33, 17, 38, 24);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (14, 'eget orci vehicula condimentum', 2, 34, 26, 41);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (8, 'cras non velit', 49, 20, 11, 4);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (54, 'libero nam dui proin leo', 12, 40, 6, 3);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (11, 'sapien quis libero nullam sit', 45, 9, 27, 11);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (35, 'eleifend luctus', 16, 19, 21, 8);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (29, 'et', 16, 18, 15, 18);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (36, 'amet turpis elementum ligula vehicula', 54, 28, 31, 13);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (31, 'nisi venenatis tristique fusce', 37, 29, 15, 32);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (13, 'mauris non ligula pellentesque', 25, 26, 14, 38);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (38, 'in magna bibendum imperdiet', 48, 35, 11, 25);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (18, 'justo', 51, 13, 12, 42);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (39, 'etiam pretium', 48, 11, 29, 8);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (36, 'nisl venenatis lacinia aenean sit', 42, 38, 15, 26);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (17, 'non pretium quis', 15, 12, 7, 41);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (21, 'ornare imperdiet sapien urna', 55, 17, 17, 7);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (9, 'hendrerit at vulputate vitae', 2, 34, 27, 38);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (12, 'vivamus tortor', 9, 11, 34, 46);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (42, 'ipsum integer a', 31, 12, 17, 28);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (35, 'posuere cubilia curae mauris viverra', 24, 32, 7, 7);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (21, 'sed magna at', 11, 6, 24, 13);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (47, 'rutrum nulla', 52, 13, 7, 30);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (32, 'felis sed', 42, 11, 32, 31);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (32, 'ipsum praesent blandit lacinia erat', 23, 30, 10, 4);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (38, 'at ipsum', 37, 31, 16, 34);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (3, 'vestibulum', 12, 39, 30, 16);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (55, 'augue', 5, 24, 36, 31);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (42, 'velit eu est congue', 6, 3, 14, 9);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (42, 'vel nulla eget eros elementum', 24, 13, 34, 22);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (23, 'risus praesent', 17, 12, 38, 23);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (17, 'erat', 48, 31, 14, 32);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (50, 'id ornare imperdiet', 49, 6, 32, 31);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (7, 'fermentum justo nec', 55, 31, 11, 34);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (4, 'id sapien in sapien iaculis', 16, 16, 36, 20);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (19, 'pellentesque eget nunc', 36, 16, 33, 6);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (24, 'ac nulla sed', 15, 35, 24, 35);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (29, 'blandit', 34, 25, 26, 16);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (25, 'cursus urna', 28, 11, 36, 26);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (15, 'ipsum', 19, 12, 8, 40);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (52, 'id sapien in sapien', 8, 26, 19, 11);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (51, 'maecenas leo odio condimentum', 26, 14, 20, 30);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (7, 'in imperdiet et', 52, 24, 17, 15);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (26, 'morbi non quam nec', 3, 25, 4, 27);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (18, 'posuere cubilia curae', 14, 39, 9, 44);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (27, 'ut ultrices', 10, 21, 8, 10);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (8, 'at nibh in hac', 36, 17, 34, 43);
insert into AdminReport (report_code, description, status, reporter_id, reported_id, offer_id) values (40, 'nec euismod scelerisque', 42, 40, 31, 3);
