USE `goods4goods`;

INSERT INTO UserReport (report_code, description, reporter_id, reported_id, offer_id, reviewer_id) VALUES
(3, 'Item condition not as described', 2, 3, 1, 1),
(1, 'User made an offensive comment', 1, 2, 3, 3);

insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (38, 'habitasse platea dictumst morbi', 8, 12, 22, 13, 9);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (46, 'pede malesuada in', 2, 9, 12, 10, 25);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (48, 'ut nulla sed accumsan', 20, 18, 9, 26, 22);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (8, 'ultrices aliquet maecenas', 26, 1, 21, 14, 40);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (22, 'elementum nullam', 43, 5, 27, 22, 16);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (45, 'at', 42, 21, 6, 31, 38);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (39, 'mi', 7, 33, 11, 35, 30);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (54, 'interdum mauris ullamcorper', 50, 40, 8, 15, 13);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (55, 'donec diam neque vestibulum eget', 47, 20, 7, 13, 34);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (24, 'justo in hac habitasse', 25, 34, 24, 35, 28);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (46, 'cum sociis', 20, 23, 11, 16, 4);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (24, 'erat volutpat in', 23, 30, 35, 44, 24);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (44, 'tempus semper est quam', 26, 8, 5, 36, 8);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (22, 'hac habitasse platea dictumst aliquam', 37, 39, 36, 8, 16);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (45, 'nibh in', 25, 19, 10, 37, 19);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (7, 'bibendum morbi', 10, 27, 40, 38, 39);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (35, 'ultrices posuere cubilia curae', 31, 6, 17, 11, 26);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (34, 'habitasse platea dictumst morbi vestibulum', 17, 5, 17, 38, 39);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (41, 'purus aliquet', 50, 20, 22, 43, 19);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (53, 'eros vestibulum ac est', 53, 12, 27, 36, 3);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (10, 'erat quisque erat', 1, 13, 8, 34, 6);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (2, 'penatibus et', 51, 38, 1, 26, 38);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (8, 'eu est', 51, 10, 16, 12, 35);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (5, 'lacus', 27, 30, 35, 36, 4);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (40, 'bibendum imperdiet', 47, 26, 33, 35, 37);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (36, 'vulputate justo', 12, 29, 9, 26, 2);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (25, 'mauris', 22, 26, 8, 5, 2);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (21, 'bibendum morbi', 55, 29, 11, 48, 12);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (2, 'velit', 42, 21, 40, 14, 12);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (30, 'ut suscipit a feugiat', 50, 2, 36, 8, 3);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (39, 'sagittis sapien cum sociis', 41, 24, 19, 29, 28);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (40, 'libero non mattis pulvinar nulla', 50, 14, 12, 10, 37);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (25, 'tortor quis turpis sed', 47, 6, 9, 39, 21);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (31, 'augue', 39, 5, 36, 33, 17);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (31, 'sodales scelerisque mauris sit', 4, 30, 37, 37, 3);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (15, 'dui proin leo odio porttitor', 36, 39, 25, 5, 28);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (45, 'id sapien in', 26, 35, 3, 42, 17);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (32, 'integer', 20, 2, 29, 36, 15);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (24, 'suspendisse potenti nullam porttitor', 18, 36, 26, 11, 33);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (5, 'erat id mauris vulputate', 24, 8, 27, 15, 30);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (34, 'viverra pede ac diam', 47, 3, 3, 24, 21);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (36, 'odio', 28, 37, 15, 2, 26);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (54, 'proin eu mi', 24, 35, 20, 4, 18);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (44, 'tortor duis mattis', 31, 23, 14, 43, 28);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (39, 'justo', 20, 9, 9, 45, 36);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (28, 'nulla suscipit', 15, 38, 23, 46, 17);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (3, 'ut tellus nulla ut', 14, 26, 16, 38, 17);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (36, 'nibh quisque', 5, 5, 40, 23, 29);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (5, 'in hac', 44, 6, 20, 37, 18);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (6, 'sed interdum', 53, 24, 21, 21, 31);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (50, 'erat volutpat in', 2, 7, 37, 7, 36);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (21, 'sapien non mi integer', 27, 4, 1, 46, 40);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (48, 'felis sed interdum', 48, 17, 24, 20, 24);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (19, 'lacus at turpis donec posuere', 38, 27, 17, 20, 25);
insert into UserReport (report_code, description, status, reporter_id, reported_id, offer_id, reviewer_id) values (18, 'potenti', 44, 12, 39, 12, 36);
